-- 0005 · rollback
DROP TABLE IF EXISTS outbox CASCADE;
DROP TABLE IF EXISTS events CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS approvals CASCADE;
DROP TABLE IF EXISTS approval_policies CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS activities CASCADE;
DROP TABLE IF EXISTS links CASCADE;

DROP FUNCTION IF EXISTS sw_audit_append_only();
DROP TYPE IF EXISTS sw_approval_status;
DROP TYPE IF EXISTS sw_link_relation;
